tables:
  User:
    table_name: users
    description: "システムに登録されるユーザーの情報。"
    columns:
      id: {type: Integer, primary_key: true, autoincrement: true, comment: "ユーザーID"}
      name: {type: String, length: 100, nullable: false, comment: "ユーザー名"}
      email: {type: String, length: 255, unique: true, nullable: false, comment: "メールアドレス"}
      created_at: {type: DateTime, default: 'func.now()', comment: "作成日時"}
  Product:
    table_name: products
    description: "販売する商品の情報。"
    columns:
      id: {type: Integer, primary_key: true, autoincrement: true, comment: "商品ID"}
      name: {type: String, length: 255, nullable: false, comment: "商品名"}
      price: {type: Integer, nullable: false, default: 0, comment: "商品価格"}
      category: {type: String, length: 50, nullable: true, index: true, comment: "商品のカテゴリ。例: Electronics, Books"}
      stock_quantity: {type: Integer, nullable: false, default: 0, comment: "在庫数"}